import websiteApi from '@/api/website';

export interface PublishRequest {
  websiteId: string;
  subdomain?: string;
  customDomain?: string;
}

export interface PublishResponse {
  success: boolean;
  url: string;
  publishedAt: string;
  sslEnabled: boolean;
  status: 'active' | 'pending' | 'error';
  message?: string;
}

export interface DomainConfig {
  domain: string;
  type: 'subdomain' | 'custom';
  status: 'active' | 'pending' | 'error';
  sslEnabled: boolean;
  dnsRecords?: {
    A?: string;
    CNAME?: string;
    TXT?: string[];
  };
  addedAt: string;
}

class PublishService {
  async publishWebsite(request: PublishRequest): Promise<PublishResponse> {
    try {
      const response = await websiteApi.publishWebsite(request.websiteId, {
        subdomain: request.subdomain,
        customDomain: request.customDomain,
      });
      return response.data;
    } catch (error) {
      console.error('Publishing failed:', error);
      throw new Error('Failed to publish website');
    }
  }

  async getDomains(websiteId: string): Promise<DomainConfig[]> {
    try {
      const response = await websiteApi.getDomains(websiteId);
      return response.data.domains;
    } catch (error) {
      console.error('Failed to fetch domains:', error);
      throw new Error('Failed to fetch domains');
    }
  }

  async addDomain(websiteId: string, domain: string): Promise<DomainConfig> {
    try {
      const response = await websiteApi.addDomain(websiteId, domain);
      return response.data.domain;
    } catch (error) {
      console.error('Failed to add domain:', error);
      throw new Error('Failed to add domain');
    }
  }

  async removeDomain(websiteId: string, domain: string): Promise<void> {
    try {
      await websiteApi.removeDomain(websiteId, domain);
    } catch (error) {
      console.error('Failed to remove domain:', error);
      throw new Error('Failed to remove domain');
    }
  }

  async verifyDomain(websiteId: string, domain: string): Promise<{ verified: boolean; dnsRecords: any }> {
    try {
      const response = await websiteApi.verifyDomain(websiteId, domain);
      return response.data;
    } catch (error) {
      console.error('Domain verification failed:', error);
      throw new Error('Failed to verify domain');
    }
  }

  /**
   * Generate static site files (for export/download)
   */
  async generateStaticSite(websiteId: string): Promise<Blob> {
    try {
      // Mock static site generation
      const htmlContent = this.generateMockHTML(websiteId);
      return new Blob([htmlContent], { type: 'text/html' });
    } catch (error) {
      console.error('Failed to generate static site:', error);
      throw new Error('Failed to generate static site');
    }
  }

  private generateMockHTML(websiteId: string): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website ${websiteId}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { background: #f8f9fa; padding: 20px; margin-bottom: 20px; }
        .footer { background: #f8f9fa; padding: 20px; margin-top: 20px; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>Welcome to Your Website</h1>
            <p>Generated by Buildora Website Builder</p>
        </header>
        
        <main>
            <section>
                <h2>About This Site</h2>
                <p>This is a static website generated from your Buildora project.</p>
            </section>
        </main>
        
        <footer class="footer">
            <p>&copy; 2024 Website ${websiteId}. Powered by Buildora.</p>
        </footer>
    </div>
</body>
</html>`;
  }
}

export const publishService = new PublishService();
