import { v4 as uuidv4 } from 'uuid';

export const createBusinessNavbar = () => ({
  id: uuidv4(),
  type: 'navbar',
  name: 'Business Navbar',
  visible: true,
  logo: { text: 'Elevate', imageUrl: '', font: 'Inter' },
  links: [
    { id: uuidv4(), label: 'Solutions', href: '#solutions' },
    { id: uuidv4(), label: 'Approach', href: '#approach' },
    { id: uuidv4(), label: 'Results', href: '#results' },
    { id: uuidv4(), label: 'About', href: '#about' },
    { id: uuidv4(), label: 'Contact', href: '#contact' },
  ],
  styles: {
    backgroundColor: '#ffffff',
    textColor: '#0f172a',
    height: '80px',
    sticky: true,
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
});

export const createBusinessHeroSection = () => ({
  id: 'hero',
  type: 'hero',
  variant: 'gradient',
  name: 'Business Hero',
  visible: true,
  locked: false,
  styles: {
    useGradient: true,
    backgroundGradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 25%, #334155 50%, #475569 75%, #64748b 100%)',
    backgroundColor: '#0f172a',
    padding: '140px 0',
    minHeight: '100vh',
    color: '#ffffff',
    headingColor: '#ffffff',
    paragraphColor: '#e2e8f0',
    buttonPrimaryBg: '#3b82f6',
    buttonPrimaryText: '#ffffff',
    buttonSecondaryBg: 'transparent',
    buttonSecondaryText: '#e2e8f0',
  },
  content: {
    eyebrowText: 'Strategic Excellence Since 2010',
    headline: 'Transform Your Business into an Industry Leader',
    subheadline: 'We partner with ambitious enterprises to unlock growth potential through data-driven strategies, cutting-edge technology, and proven methodologies that deliver measurable ROI.',
    ctaText: 'Start Your Transformation',
    ctaSecondaryText: 'Watch Our Story',
    imageUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80',
    stats: [
      { value: '500+', label: 'Global Clients' },
      { value: '$2.5B', label: 'Revenue Generated' },
      { value: '98%', label: 'Client Satisfaction' },
    ],
  },
  components: [],
});

export const createBusinessCurriculumSection = () => ({
  id: 'approach',
  type: 'process',
  variant: 'timeline',
  name: 'Our Approach',
  visible: true,
  locked: false,
  styles: {
    backgroundColor: '#0f172a',
    padding: '120px 0',
    color: '#ffffff',
    headingColor: '#ffffff',
    paragraphColor: '#e2e8f0',
  },
  content: {
    headline: 'Our Proven Transformation Framework',
    subheadline: 'A systematic approach that delivers consistent, measurable results across industries and markets.',
    steps: [
      {
        id: uuidv4(),
        title: 'Discovery & Analysis',
        description: 'Deep dive into your business ecosystem, market position, and growth opportunities through comprehensive audits and stakeholder interviews.',
        icon: 'Search',
        duration: '2-4 Weeks',
        deliverables: ['Business Audit', 'Market Analysis', 'Opportunity Matrix'],
      },
      {
        id: uuidv4(),
        title: 'Strategy Design',
        description: 'Craft tailored solutions with clear objectives, KPIs, and implementation roadmaps aligned with your vision and market realities.',
        icon: 'Lightbulb',
        duration: '3-6 Weeks',
        deliverables: ['Strategic Roadmap', 'Implementation Plan', 'Success Metrics'],
      },
      {
        id: uuidv4(),
        title: 'Implementation & Execution',
        description: 'Execute with precision through agile methodologies, continuous monitoring, and iterative improvements to ensure optimal outcomes.',
        icon: 'Rocket',
        duration: '3-12 Months',
        deliverables: ['Solution Deployment', 'Team Training', 'Performance Monitoring'],
      },
      {
        id: uuidv4(),
        title: 'Optimization & Scale',
        description: 'Refine processes, scale successful initiatives, and establish frameworks for continuous improvement and sustainable growth.',
        icon: 'TrendingUp',
        duration: 'Ongoing',
        deliverables: ['Performance Optimization', 'Scale Strategy', 'Continuous Improvement'],
      },
    ],
  },
  components: [],
});

export const createBusinessAboutSection = () => ({
  id: 'about',
  type: 'about',
  variant: 'split',
  name: 'Business About',
  visible: true,
  locked: false,
  styles: {
    backgroundColor: '#ffffff',
    padding: '120px 0',
    color: '#0f172a',
    headingColor: '#0f172a',
    paragraphColor: '#475569',
  },
  content: {
    headline: 'Pioneering Business Excellence for Over a Decade',
    description: 'Elevate has been the catalyst behind countless business transformations since 2010. Our approach combines deep industry expertise with cutting-edge technology to deliver solutions that not only solve today\'s challenges but anticipate tomorrow\'s opportunities. We believe in building lasting partnerships that drive sustainable growth and create competitive advantages.',
    features: [
      {
        id: uuidv4(),
        title: 'Strategic Vision',
        description: 'Long-term thinking with agile execution',
        icon: 'Target',
      },
      {
        id: uuidv4(),
        title: 'Data-Driven',
        description: 'Decisions backed by real-time analytics',
        icon: 'BarChart3',
      },
      {
        id: uuidv4(),
        title: 'Global Reach',
        description: 'Local expertise with worldwide presence',
        icon: 'Globe',
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80',
  },
  components: [],
});

export const createBusinessServicesSection = () => ({
  id: 'solutions',
  type: 'services',
  variant: 'grid',
  name: 'Business Solutions',
  visible: true,
  locked: false,
  styles: {
    backgroundColor: '#f8fafc',
    padding: '120px 0',
    color: '#0f172a',
    headingColor: '#0f172a',
    paragraphColor: '#475569',
  },
  content: {
    headline: 'Comprehensive Business Solutions',
    subheadline: 'End-to-end services designed to transform every aspect of your enterprise',
    services: [
      {
        id: uuidv4(),
        icon: 'TrendingUp',
        title: 'Growth Strategy',
        description: 'Develop data-driven roadmaps that align market opportunities with your core strengths for sustainable expansion.',
        features: ['Market Analysis', 'Competitive Intelligence', 'Revenue Optimization'],
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
      },
      {
        id: uuidv4(),
        icon: 'Cpu',
        title: 'Digital Innovation',
        description: 'Transform your enterprise with AI, automation, and cloud solutions that drive efficiency and competitive advantage.',
        features: ['AI Integration', 'Cloud Migration', 'Process Automation'],
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
      },
      {
        id: uuidv4(),
        icon: 'Users',
        title: 'Talent Excellence',
        description: 'Build high-performing teams through strategic HR solutions, leadership development, and culture transformation.',
        features: ['Executive Search', 'Team Development', 'Culture Design'],
        imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80',
      },
      {
        id: uuidv4(),
        icon: 'Globe',
        title: 'Market Expansion',
        description: 'Navigate global markets with confidence through localized strategies, compliance expertise, and partnership networks.',
        features: ['Market Entry', 'Localization', 'Global Partnerships'],
        imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80',
      },
      {
        id: uuidv4(),
        icon: 'Shield',
        title: 'Risk Management',
        description: 'Protect your enterprise with comprehensive risk assessment, compliance frameworks, and business continuity planning.',
        features: ['Risk Assessment', 'Compliance Management', 'Business Continuity'],
        imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=80',
      },
      {
        id: uuidv4(),
        icon: 'Zap',
        title: 'Operational Excellence',
        description: 'Optimize processes, reduce costs, and enhance productivity through lean methodologies and continuous improvement.',
        features: ['Process Optimization', 'Cost Reduction', 'Quality Management'],
        imageUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&q=80',
      },
    ],
  },
  components: [],
});

export const createBusinessTestimonialsSection = () => ({
  id: 'results',
  type: 'testimonials',
  variant: 'cards',
  name: 'Client Success Stories',
  visible: true,
  locked: false,
  styles: {
    backgroundColor: '#ffffff',
    padding: '120px 0',
    color: '#0f172a',
    headingColor: '#0f172a',
    paragraphColor: '#475569',
  },
  content: {
    headline: 'Transformative Results, Trusted Partnerships',
    subheadline: 'Discover how industry leaders have achieved breakthrough success with our strategic guidance.',
    testimonials: [
      {
        id: uuidv4(),
        quote: 'Elevate\'s strategic framework transformed our entire business model. We achieved 45% revenue growth and expanded to 12 new markets within 18 months. Their expertise in digital transformation is unmatched.',
        name: 'Jennifer Martinez',
        role: 'CEO, InnovateTech Solutions',
        company: 'Fortune 500 Technology Company',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
        rating: 5,
        results: ['45% Revenue Growth', '12 New Markets', '18 Month Timeline'],
      },
      {
        id: uuidv4(),
        quote: 'The operational excellence program delivered immediate results. We reduced operational costs by 35% while improving customer satisfaction scores by 40%. Their data-driven approach is revolutionary.',
        name: 'David Thompson',
        role: 'COO, Global Logistics Partners',
        company: 'Leading Supply Chain Company',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
        rating: 5,
        results: ['35% Cost Reduction', '40% CSAT Improvement', '6 Month ROI'],
      },
      {
        id: uuidv4(),
        quote: 'Their talent transformation program completely rebuilt our leadership team. We now have the strongest management team in our industry, driving innovation and growth at unprecedented levels.',
        name: 'Sarah Williams',
        role: 'CHRO, Apex Financial Group',
        company: 'Global Financial Services Firm',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
        rating: 5,
        results: ['95% Retention Rate', '60% Leadership Growth', 'Industry Recognition'],
      },
    ],
  },
  components: [],
});

export const createBusinessCTASection = () => ({
  id: 'cta',
  type: 'cta',
  variant: 'gradient',
  name: 'Business CTA',
  visible: true,
  locked: false,
  styles: {
    backgroundGradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 50%, #1e40af 100%)',
    backgroundColor: '#3b82f6',
    padding: '120px 0',
    color: '#ffffff',
    headingColor: '#ffffff',
    paragraphColor: '#e0f2fe',
    buttonPrimaryBg: '#ffffff',
    buttonPrimaryText: '#1e40af',
    buttonSecondaryBg: 'transparent',
    buttonSecondaryText: '#ffffff',
  },
  content: {
    headline: 'Ready to Elevate Your Business to New Heights?',
    subheadline: 'Join 500+ industry leaders who have transformed their enterprises with our proven methodologies. Schedule your complimentary strategy session today.',
    ctaText: 'Book Your Free Strategy Session',
    ctaSecondaryText: 'Download Success Stories',
    features: [
      'Comprehensive Business Analysis',
      'Customized Growth Roadmap',
      'No-Obligation Consultation',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80',
  },
  components: [],
});

export const createBusinessContactSection = () => ({
  id: 'contact',
  type: 'contact',
  name: 'Business Contact',
  visible: true,
  locked: false,
  styles: {
    backgroundColor: '#f8fafc',
    padding: '100px 0',
    color: '#1e293b',
  },
  content: {
    headline: 'Get In Touch',
    subheadline: 'Tell us about your business challenges. Our experts will get back to you within 24 hours.',
    email: 'contact@bizcorp.com',
    phone: '+1 (800) 555-0199',
    address: '1200 Corporate Drive, Suite 400, New York, NY 10001',
    fields: [
      { id: uuidv4(), label: 'Full Name', type: 'text', placeholder: 'John Smith', required: true },
      { id: uuidv4(), label: 'Business Email', type: 'email', placeholder: 'john@company.com', required: true },
      { id: uuidv4(), label: 'Message', type: 'textarea', placeholder: 'Tell us how we can help...', required: true },
    ],
    submitText: 'Send Message',
  },
  components: [],
});

export const createBusinessFooter = () => ({
  id: uuidv4(),
  type: 'footer',
  name: 'Business Footer',
  visible: true,
  logo: { text: 'Elevate', imageUrl: '' },
  description: 'Transforming businesses into industry leaders through strategic excellence and innovative solutions.',
  socialLinks: [
    { id: uuidv4(), platform: 'linkedin', href: '#' },
    { id: uuidv4(), platform: 'twitter', href: '#' },
    { id: uuidv4(), platform: 'facebook', href: '#' },
    { id: uuidv4(), platform: 'instagram', href: '#' },
  ],
  columns: [
    {
      id: uuidv4(),
      title: 'Solutions',
      links: [
        { id: uuidv4(), label: 'Growth Strategy', href: '#solutions' },
        { id: uuidv4(), label: 'Digital Innovation', href: '#solutions' },
        { id: uuidv4(), label: 'Talent Excellence', href: '#solutions' },
        { id: uuidv4(), label: 'Market Expansion', href: '#solutions' },
      ],
    },
    {
      id: uuidv4(),
      title: 'Company',
      links: [
        { id: uuidv4(), label: 'About Us', href: '#about' },
        { id: uuidv4(), label: 'Our Approach', href: '#approach' },
        { id: uuidv4(), label: 'Success Stories', href: '#results' },
        { id: uuidv4(), label: 'Careers', href: '#' },
      ],
    },
    {
      id: uuidv4(),
      title: 'Resources',
      links: [
        { id: uuidv4(), label: 'Case Studies', href: '#' },
        { id: uuidv4(), label: 'White Papers', href: '#' },
        { id: uuidv4(), label: 'Blog', href: '#' },
        { id: uuidv4(), label: 'Podcast', href: '#' },
      ],
    },
    // {
    //   id: uuidv4(),
    //   title: 'Legal',
    //   links: [
    //     { id: uuidv4(), label: 'Privacy Policy', href: '/privacy' },
    //     { id: uuidv4(), label: 'Terms of Service', href: '/terms' },
    //     { id: uuidv4(), label: 'Cookie Policy', href: '/cookies' },
    //   ],
    // },
  ],
  copyright: `© ${new Date().getFullYear()} Elevate Business Solutions. All rights reserved.`,
  styles: {
    backgroundColor: '#0f172a',
    textColor: '#94a3b8',
    padding: '80px 0 40px 0',
  },
});

export const getBusinessPage = () => ({
  id: uuidv4(),
  name: 'Home',
  slug: '/',
  meta: {
    title: 'BizCorp - Strategic Business Solutions',
    description: 'Empowering enterprises with cutting-edge technology and strategic consulting.'
  },
  navbar: createBusinessNavbar(),
  sections: [
    createBusinessHeroSection(),
    createBusinessAboutSection(),
    createBusinessServicesSection(),
    createBusinessCurriculumSection(),
    createBusinessTestimonialsSection(),
    createBusinessCTASection(),
    createBusinessContactSection(),
  ],
  footer: createBusinessFooter(),
  globalStyles: {
    fontFamily: 'Inter',
    primaryColor: '#3b82f6',
    backgroundColor: '#ffffff',
  },
});
